name: Sleep for 3 Minutes

on:
  pull_request:
    branches:
      - main
      - test1

jobs:
  sleep_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 3 minutes
        run: sleep 180
