name: Sleep-for-3-Minutes

on:
  pull_request:
    branches:
      - main
      - test1

concurrency:
  group: shared-integration-tests
  cancel-in-progress: false

jobs:
  sleep_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 3 minutes
        run: sleep 180
